name: depim
version: 0.1.0
author: Jean-Pascal Milcent <jpm@clapas.org>
description: Gestion des d√©pouillements en ligne.
homepage: http://www.depim.net
dependencies:
  browser: any
  json_object: any
  web_ui: any
